baseURL = 'https://samibr.github.io/gitmath/'
relativeURLs = true
languageCode = 'en-us'
title = 'GitMath: A Collaborative Math Problem Database'

theme = 'lugo'

[params]
  favicon = "favicon.svg"
  stylesheet = "/style.css"
  indexarticles = 50
  description = 'Provide a simple and free online Mathematics Problem Book'
  keywords = ["math", "problems", "solutions"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

