title = "Based Mathematics"
baseURL = 'https://based-mathematics.netlify.app/'
languageCode = 'en-us'


[params.math]
enable = false # whether to enable math typesetting
use = "katex"  # katex or mathjax


[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  #relatedtext = "Related:"
  favicon = "/favicon.ico"
